name: checador
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  video_player: ^2.7.0
  video_player_win: ^3.1.1
  path_provider: ^2.1.2
  http: ^0.13.6
  geolocator: ^10.1.0
  permission_handler: ^11.3.0
  shared_preferences: ^2.2.2
  sqflite_common_ffi: ^2.3.0
  connectivity_plus: ^5.0.2
  sqflite: ^2.3.0
  path: ^1.8.0
  url_launcher: ^6.2.5



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/logo.jpeg
    - assets/usuario.jpg
    - assets/videos/fondo.mp4